
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[252] =
    {   0,
        0,    0,    0,    0,  101,   99,   88,   89,   76,   91,
       99,   82,   75,   99,   70,   71,   80,   79,   67,   78,
       74,   81,   96,   68,   62,   83,   69,   84,   87,   97,
       72,   73,   85,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   63,   86,
       65,   77,    8,   10,    7,    9,   61,   91,   90,    0,
        0,   47,   66,   56,   48,    0,    0,    0,   45,   53,
       43,   54,   44,   55,    4,    3,   46,    0,   96,    0,
       73,   64,   72,   52,   58,   60,   59,   51,   97,   98,
       49,   97,   97,   97,   97,   97,   97,   97,   19,   97,

       97,   97,   97,   25,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   50,   57,    8,    7,    6,
        5,    0,    0,    0,   92,    0,    0,    0,   92,    3,
       95,   94,   42,   41,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   23,   97,   26,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,    0,    0,   93,    0,    0,   92,   11,   13,   97,
       14,   15,   97,   97,   97,   97,   21,   97,   24,   27,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       38,   97,   97,    0,    0,   12,   16,   97,   97,   97,

       22,   97,   29,   97,   97,   97,   97,   97,   97,   36,
       97,   97,   40,    0,    0,   97,   97,   20,   28,   30,
       31,   32,   33,   34,   97,   97,   97,    0,    0,   97,
       18,   35,   97,   97,    0,    0,   17,   37,   39,    0,
        0,    0,    2,    2,    2,    0,    0,    0,    0,    1,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   27,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   27,
       53,   54,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    5,    4,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    8,    1,    1,
        1,    9,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[265] =
    {   0,
        0,    0,   56,   57,  573,  578,  578,  578,  547,  564,
       25,   38,   55,   55,  578,  578,  545,   53,  578,   56,
      578,   58,   66,  535,  578,   70,  527,   63,  578,  514,
      578,  578,  500,   40,   61,   64,   68,   67,   71,   70,
       73,   74,   84,   90,   72,   79,   92,   94,  578,  100,
      578,  578,    0,  578,  114,  504,  578,  509,  578,  465,
      449,  578,  578,  578,  578,  450,  449,  154,  578,  578,
      578,  578,  578,  578,  578,    0,  578,  109,  116,  121,
      578,  578,  578,  434,  578,  578,  578,  433,  428,  578,
      578,   98,  110,  115,  117,  116,  118,  120,  122,  123,

      131,  133,  126,  426,  135,  138,  140,  141,  139,  157,
      153,  149,  168,  169,  172,  578,  578,    0,  161,  578,
      578,  415,  417,  441,  578,  440,  439,  436,  435,    0,
      187,  195,  578,  578,  163,  174,  190,  183,  191,  193,
      194,  197,  198,  200,  416,  201,  415,  204,  202,  206,
      211,  208,  209,  212,  216,  219,  221,  220,  223,  235,
      226,  401,  398,  578,  430,  429,  578,  410,  409,  222,
      408,  407,  229,  232,  239,  242,  406,  243,  405,  402,
      244,  246,  247,  248,  249,  251,  252,  260,  253,  255,
      401,  254,  270,  384,  377,  398,  397,  271,  273,  272,

      396,  274,  395,  276,  282,  278,  277,  283,  280,  394,
      286,  291,  393,  383,  383,  293,  296,  390,  389,  388,
      387,  386,  385,  328,  297,  294,  299,  348,  314,  300,
      322,  321,  305,  301,  344,  330,  319,  318,  316,  353,
      408,    0,  428,  336,    0,  322,  296,  182,  145,  578,
      578,  482,  491,  500,  504,  513,  522,  531,  540,  549,
      558,  565,   66,  570
    } ;

static const flex_int16_t yy_def[265] =
    {   0,
      251,    1,  252,  252,  251,  251,  251,  251,  251,  253,
      251,  251,  251,  254,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  255,
      251,  251,  251,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  251,  251,
      251,  251,  256,  251,  251,  251,  251,  253,  251,  251,
      251,  251,  251,  251,  251,  257,  251,  258,  251,  251,
      251,  251,  251,  251,  251,  259,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  255,  251,
      251,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  251,  251,  256,  251,  251,
      251,  251,  251,  257,  251,  260,  261,  257,  251,  259,
      251,  251,  251,  251,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  251,  251,  251,  260,  261,  251,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  251,  251,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  251,  251,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  251,  251,  255,
      255,  255,  255,  255,  262,  251,  255,  255,  255,  251,
      251,  263,  240,  243,  240,  264,  251,  264,  251,  251,
        0,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251
    } ;

static const flex_int16_t yy_nxt[637] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       24,   25,   26,   27,   28,   29,   30,   31,    6,   32,
       33,   30,   34,   35,   36,   37,   38,   39,   40,   30,
       41,   30,   42,   30,   30,   30,   43,   44,   45,   46,
       47,   48,   30,   30,   49,   50,   51,   52,   54,   54,
       60,   62,   63,   64,   67,   61,   70,   90,   55,   55,
       75,   72,  246,   56,   56,   76,   71,   82,   65,   73,
       74,   77,   78,   68,   79,   79,   87,   88,   90,   92,
       83,   90,   84,   85,   90,   90,   95,   90,   90,   90,

       90,   90,   80,   96,   98,   93,   90,   94,   97,  100,
      104,   90,   99,  101,  103,  102,  105,   90,  106,   90,
      107,   90,  113,  116,  112,   90,  119,  131,  131,  108,
      109,  120,   78,  115,   79,   79,  114,   90,  110,  132,
      132,  111,   90,   90,   90,   90,  135,   90,  139,   90,
       90,  137,   80,   90,  136,  117,  127,  141,   90,  128,
       90,  140,   90,  129,  138,   90,   90,   90,   90,  250,
      143,  142,  128,  119,  146,  144,   90,  151,  120,  145,
       90,  148,  128,  147,   90,  150,  128,  128,  149,  153,
       90,  128,  152,  155,  156,   90,   90,  128,  247,   90,

      128,   90,  128,  154,  128,  131,  131,  168,  157,  159,
       90,  160,  161,  132,  132,  158,  169,   90,   90,  171,
       90,   90,  170,   80,   90,   90,  175,   90,   90,   90,
      176,   90,  178,   90,  177,   90,   90,  172,   90,   90,
      173,  174,  180,   90,  184,  179,   90,   90,   90,   90,
       90,  181,  182,   90,  183,  188,   90,  185,  191,   90,
      190,  186,   90,  196,  187,  189,   90,  192,  193,   90,
       90,   90,  198,   90,   90,   90,   90,  197,   90,   90,
       90,   90,   90,  204,  200,  207,  208,   90,  199,  206,
      202,  201,  205,  211,  203,  209,  210,   90,   90,   90,

       90,   90,  212,   90,   90,   90,  213,   90,  218,   90,
       90,  220,  222,   90,  216,  217,  225,  219,   90,  221,
       90,   90,  224,   90,   90,  223,   90,   90,   90,  226,
      233,  227,   90,  241,  232,  249,  237,  239,  247,  244,
      238,  234,  230,   90,  231,   90,   90,  235,   90,   90,
      236,  235,  242,  243,  243,   90,  244,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  245,  245,  243,  243,  243,  243,  243,  243,  245,
      243,  243,  243,  243,  243,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  243,  243,  243,
      243,  241,   90,   90,   90,   90,   90,   90,  229,  228,
       90,   90,   90,   90,   90,   90,  215,  214,   90,   90,
      242,  243,   90,   90,   90,   90,   90,   90,  164,  164,
      195,  194,   90,   90,  125,  167,  243,  243,  164,  164,
      164,  163,  162,   90,  243,   90,  134,  133,  125,  125,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   58,  123,   58,   58,   58,   58,   58,   58,   58,

       66,  122,   66,   66,   66,   66,   66,   66,   66,   89,
       89,   89,   89,  118,   59,  118,  121,  118,  118,  118,
      118,  118,  124,   91,  124,  124,  124,  124,  124,  124,
      124,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      130,   90,  130,  130,  130,  130,  130,  130,  130,  165,
       86,  165,  165,  165,  165,  165,  165,  165,  166,   81,
      166,  166,  166,  166,  166,  166,  166,  240,   69,   59,
       57,  240,  251,  240,  248,  248,  248,    5,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251
    } ;

static const flex_int16_t yy_chk[637] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
       11,   12,   12,   13,   14,   11,   18,   34,    3,    4,
       22,   20,  263,    3,    4,   22,   18,   26,   13,   20,
       20,   22,   23,   14,   23,   23,   28,   28,   35,   34,
       26,   36,   26,   26,   38,   37,   36,   40,   39,   45,

       41,   42,   23,   36,   37,   35,   46,   35,   36,   38,
       41,   43,   37,   39,   40,   39,   41,   44,   42,   47,
       43,   48,   46,   50,   45,   92,   55,   78,   78,   44,
       44,   55,   79,   48,   79,   79,   47,   93,   44,   80,
       80,   44,   94,   96,   95,   97,   92,   98,   96,   99,
      100,   94,   79,  103,   93,   50,   68,   98,  101,   68,
      102,   97,  105,   68,   95,  106,  109,  107,  108,  249,
      100,   99,   68,  119,  103,  101,  112,  109,  119,  102,
      111,  106,   68,  105,  110,  108,   68,   68,  107,  110,
      135,   68,  109,  111,  112,  113,  114,   68,  248,  115,

       68,  136,   68,  110,   68,  131,  131,  135,  113,  114,
      138,  114,  115,  132,  132,  113,  136,  137,  139,  138,
      140,  141,  137,  131,  142,  143,  141,  144,  146,  149,
      142,  148,  144,  150,  143,  152,  153,  139,  151,  154,
      140,  140,  148,  155,  152,  146,  156,  158,  157,  170,
      159,  149,  150,  161,  151,  156,  173,  153,  159,  174,
      158,  154,  160,  170,  155,  157,  175,  160,  161,  176,
      178,  181,  174,  182,  183,  184,  185,  173,  186,  187,
      189,  192,  190,  183,  176,  186,  187,  188,  175,  185,
      181,  178,  184,  190,  182,  188,  189,  193,  198,  200,

      199,  202,  192,  204,  207,  206,  193,  209,  200,  205,
      208,  204,  206,  211,  198,  199,  209,  202,  212,  205,
      216,  226,  208,  217,  225,  207,  227,  230,  234,  211,
      226,  212,  233,  236,  225,  247,  230,  234,  246,  244,
      233,  227,  216,  239,  217,  238,  237,  235,  232,  231,
      229,  228,  236,  240,  240,  224,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  241,  223,  222,  221,  220,  219,  218,  215,  214,
      213,  210,  203,  201,  197,  196,  195,  194,  191,  180,
      241,  243,  179,  177,  172,  171,  169,  168,  166,  165,
      163,  162,  147,  145,  129,  128,  243,  243,  127,  126,
      124,  123,  122,  104,  243,   89,   88,   84,   67,   66,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  253,   61,  253,  253,  253,  253,  253,  253,  253,

      254,   60,  254,  254,  254,  254,  254,  254,  254,  255,
      255,  255,  255,  256,   58,  256,   56,  256,  256,  256,
      256,  256,  257,   33,  257,  257,  257,  257,  257,  257,
      257,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      259,   30,  259,  259,  259,  259,  259,  259,  259,  260,
       27,  260,  260,  260,  260,  260,  260,  260,  261,   24,
      261,  261,  261,  261,  261,  261,  261,  262,   17,   10,
        9,  262,    5,  262,  264,  264,  264,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <stdio.h>
#include <string.h>
#include "y.tab.h"

extern void yyerror(const char *);
extern int yylineno;
int curly_count=0;

#define TABLE_SIZE 1000

struct ConstantTable{
		char constant_name[100];
		char constant_type[100];
		int exist;
	}CT[TABLE_SIZE];
	
struct SymbolTable{
		char symbol_name[100];
		char symbol_type[100];
        	char array_dimensions[100];
		char class[100];
        	char value[100];
        	char parameters[100];
		char pdl[100];
        	int line_number;
		int exist;
		int nesting_level;
	}ST[TABLE_SIZE];

int search_ConstantTable(char* str) { 
for (int i = 0; i < TABLE_SIZE; i++) { 
if (CT[i].exist == 1 && strcmp(CT[i].constant_name, str) == 0) { 
return 1;
 	} 
} 
return 0; 
}

int search_SymbolTable(char* str) { 
for (int i = 0; i < TABLE_SIZE; i++) { 
if (ST[i].exist == 1 && strcmp(ST[i].symbol_name, str) == 0) { 
return 1;
 	} 
} 
return 0; 
}

void insert_ConstantTable(char* name, char* type){
	 if(search_ConstantTable(name))
		return;
		
	for (int i = 0; i < TABLE_SIZE; i++) {
		if(CT[i].exist == 0){
			strcpy(CT[i].constant_name, name);
			strcpy(CT[i].constant_type, type);
			CT[i].exist = 1;
			return;
		}
	}
	printf("Error: Constant table is full.\n");
}

	void insert_SymbolTable(char* name, char* type){
	 	if(search_SymbolTable(name))
			return;
		
		for (int i = 0; i < TABLE_SIZE; i++) {
			if(ST[i].exist == 0){
				strcpy(ST[i].symbol_name, name);
				strcpy(ST[i].symbol_type, type);
				strcpy(ST[i].array_dimensions, "No dimensions");
				ST[i].line_number=yylineno;
				ST[i].nesting_level=curly_count;
				strcpy(ST[i].pdl, "Not a function");
				ST[i].exist = 1;
				return;
			}
		}
		printf("Error: Symbol table is full.\n");
	}

	void insert_SymbolTable_type(char *str1, char *str2)
	{
		for(int i = 0 ; i < TABLE_SIZE ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcpy(ST[i].symbol_type,str2);
			}
		}
    }

	void insert_SymbolTable_class(char *str1, int a){
		for(int i=0;i<TABLE_SIZE;i++){
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				if(a==0){
					strcpy(ST[i].class,"STRUCTURE");
				}
				else if(a==1){
					strcpy(ST[i].class,"FUNCTION");
				}
				else if(a==2){
					strcpy(ST[i].class,"VARIABLE");
				}
			}
		}
	}

	void insert_SymbolTable_value(char *str1, char *str2)
	{
		for(int i = 0 ; i < TABLE_SIZE ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcpy(ST[i].value,str2);
			}
		}
	}

    	void insert_SymbolTable_arraydim(char *str1, char *dim)
	{
		for(int i = 0 ; i < TABLE_SIZE ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcpy(ST[i].array_dimensions,dim);
			}
		}
	}
	
	void insert_SymbolTable_pdl(char *str1, int pdl)
	{
		for(int i = 0 ; i < TABLE_SIZE ; i++)
                {
                        if(strcmp(ST[i].symbol_name,str1)==0)
                        {
                                if(pdl==0) strcpy(ST[i].pdl, "Defined");
				else if(pdl==1) strcpy(ST[i].pdl, "Declared");
                        }
                }
	}

    	void insert_SymbolTable_funcparam(char *str1, char *param)
	{
		for(int i = 0 ; i < TABLE_SIZE ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcat(ST[i].parameters," ");
                strcat(ST[i].parameters,param);
			}
		}
	}

	void insert_SymbolTable_line(char *str1, int line)
	{
		for(int i = 0 ; i < TABLE_SIZE ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				ST[i].line_number = line;
			}
		}
	}

	void printConstantTable(){
		printf("| %20s | %20s |\n", "CONSTANT","TYPE");
		for(int i = 0; i < TABLE_SIZE; ++i){
			if(CT[i].exist == 0)
				continue;
				
			printf("| %20s | %20s |\n", CT[i].constant_name, CT[i].constant_type);
		}
	}

	void printSymbolTable(){
        printf("| %10s | %10s | %18s | %15s | %10s | %30s | %10s |\n","SYMBOL NAME", "TYPE", "CLASS","DIMENSIONS","PARAMETERS","PROCEDURE DEFINITION LANGUAGE","NESTING_LEVEL");
		for(int i = 0; i < TABLE_SIZE; ++i){
			if(ST[i].exist == 0)
				continue;
			printf("| %11s | %10s | %18s | %15s | %10s | %30s |            %d  |\n", ST[i].symbol_name, ST[i].symbol_type, ST[i].class,ST[i].array_dimensions,ST[i].parameters,ST[i].pdl, ST[i].nesting_level);
		}
	}

	void printSymbolDataLine(){
        printf("| %10s |  %10s | %10s |\n","SYMBOL", "TYPE","LINE NO");
                for(int i = 0; i < TABLE_SIZE; ++i){
                        if(ST[i].exist == 0)
                                continue;
                        printf("| %10s | %11s |        %d   |\n", ST[i].symbol_name, ST[i].symbol_type, ST[i].line_number);
                }
        }

	char current_identifier[20];
	char current_type[20];
	char current_value[20];
        char current_function[20];
	char previous_operator[20];
	extern int flag;

#line 869 "lex.yy.c"

#line 871 "lex.yy.c"

#define INITIAL 0
#define MLCOMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 213 "lexer.l"


#line 216 "lexer.l"
	int nested_count = 0;
	int check_nested = 0;

#line 1096 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 252 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 578 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 219 "lexer.l"
{ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 220 "lexer.l"
{ } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 221 "lexer.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 223 "lexer.l"
{ BEGIN MLCOMMENT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 224 "lexer.l"
{ ++nested_count; 
												check_nested = 1;
											 }	
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 227 "lexer.l"
{ if (nested_count) --nested_count;
											   else{ if(check_nested){
														check_nested = 0;
														BEGIN INITIAL;
														}
													 else{
														BEGIN INITIAL;
													}
											    } 
											 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 237 "lexer.l"
; 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 "lexer.l"
;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 239 "lexer.l"
;
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 240 "lexer.l"
;
	YY_BREAK
case YY_STATE_EOF(MLCOMMENT):
#line 241 "lexer.l"
{ printf("Line No. %d ERROR: MULTI LINE COMMENT NOT CLOSED\n", yylineno); return 0;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 242 "lexer.l"
{ return AUTO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 243 "lexer.l"
{ insert_SymbolTable_line(yytext, yylineno); insert_SymbolTable(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 244 "lexer.l"
{ return BOOL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 245 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return CASE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 246 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword"); return CHAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 247 "lexer.l"
{ return CONST; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 248 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return CONTINUE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 249 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return DEFAULT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 250 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword"); return DO;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 251 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 252 "lexer.l"
{ insert_SymbolTable_line(yytext, yylineno); insert_SymbolTable(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 253 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");return FLOAT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 254 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 255 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return GOTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 256 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword"); return IF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 257 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");return INT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 258 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return LONG;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 259 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return RETURN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 260 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return SHORT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 261 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return SIGNED;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 262 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return SIZEOF;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 263 "lexer.l"
{ return STATIC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 264 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 265 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return SWITCH;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 266 "lexer.l"
{ return TYPEDEF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 267 "lexer.l"
{ return UNION; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 268 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword");  return UNSIGNED;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 269 "lexer.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 270 "lexer.l"
{ return VOLATILE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 271 "lexer.l"
{ insert_SymbolTable(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 272 "lexer.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 273 "lexer.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 274 "lexer.l"
{ return ADD_EQUAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 275 "lexer.l"
{ return SUB_EQUAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 276 "lexer.l"
{ return MUL_EQUAL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 277 "lexer.l"
{ return DIV_EQUAL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 278 "lexer.l"
{ return MOD_EQUAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 279 "lexer.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 280 "lexer.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 281 "lexer.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 282 "lexer.l"
{ return RIGHT_OP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 283 "lexer.l"
{ return LEFT_OP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 284 "lexer.l"
{ return INCREMENT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 285 "lexer.l"
{ return DECREMENT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 286 "lexer.l"
{ return PTR_OP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 287 "lexer.l"
{ return AND_OP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 288 "lexer.l"
{ return OR_OP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 289 "lexer.l"
{ return LESSER_EQUAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 290 "lexer.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 291 "lexer.l"
{ return EQUAL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 292 "lexer.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 293 "lexer.l"
{ return ';'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 294 "lexer.l"
{ curly_count++; return '{'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 295 "lexer.l"
{ return '{'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 296 "lexer.l"
{ curly_count--; return '}'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 297 "lexer.l"
{ return '}'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 298 "lexer.l"
{ return ','; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 299 "lexer.l"
{ return ':'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 300 "lexer.l"
{ return '='; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 301 "lexer.l"
{ return '('; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 302 "lexer.l"
{ return ')'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 303 "lexer.l"
{ return '['; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 304 "lexer.l"
{ return ']'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 305 "lexer.l"
{ return '.'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 306 "lexer.l"
{ return '&'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 307 "lexer.l"
{ return NOT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 308 "lexer.l"
{ return '~'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 309 "lexer.l"
{ return '-'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 310 "lexer.l"
{ return '+'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 311 "lexer.l"
{ return '*'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 312 "lexer.l"
{ return '/'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 313 "lexer.l"
{ return '%'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 314 "lexer.l"
{ return LESSER; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 315 "lexer.l"
{ return GREATER; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 316 "lexer.l"
{ return '^'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 317 "lexer.l"
{ return '|'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 318 "lexer.l"
{ return '?'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 319 "lexer.l"
{ /*whitespaces*/ }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 320 "lexer.l"
{ yylineno++; } 
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 321 "lexer.l"
{ strcpy(current_value,yytext); insert_ConstantTable(yytext,"String Constant"); return string_constant;}    
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 323 "lexer.l"
{ printf("Line No. %d ERROR: UNCLOSED STRING - %s\n", yylineno, yytext); return 0;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 325 "lexer.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 327 "lexer.l"
{printf("Line No. %d ERROR: NOT A CHARACTER - %s\n", yylineno, yytext); return 0; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 329 "lexer.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext, "Floating Constant"); return float_constant;} 
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 331 "lexer.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext, "Floating Constant"); return float_constant;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 333 "lexer.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext, "Number Constant"); return integer_constant;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 335 "lexer.l"
{strcpy(current_identifier,yytext);insert_SymbolTable(yytext,"Identifier");  return IDENTIFIER;}
	YY_BREAK
case 98:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 337 "lexer.l"
{strcpy(current_identifier,yytext);insert_SymbolTable(yytext,"Array Identifier");  return IDENTIFIER;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 340 "lexer.l"
{ flag = 1;
					  if(yytext[0] == '#')
					  printf("Line No. %d PREPROCESSOR ERROR - %s\n",yylineno, yytext);
					  else
					  printf("Line No. %d ERROR ILLEGAL CHARACTER - %s\n", yylineno, yytext);
			                  return 0;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 346 "lexer.l"
ECHO;
	YY_BREAK
#line 1679 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 252 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 252 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 251);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 346 "lexer.l"


